GAZI.LibraryApp.UI/Controllers/MenagerController.cs
using GAZI.LibraryApp.Business.BooksAppService;
using GAZI.LibraryApp.Business.BorrowBooksAppService;
using GAZI.LibraryApp.Business.MailAppService;
using GAZI.LibraryApp.Business.UsersAppService;
using GAZI.LibraryApp.Data.Entities;
using GAZI.LibraryApp.Data.Repositories.BooksRepositories;
using GAZI.LibraryApp.UI.Auth;
using GAZI.LibraryApp.UI.Models;
using Ninject;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace GAZI.LibraryApp.UI.Controllers
{
    public class MenagerController : Controller
    {
        // GET: Yonetici
        [Inject]
        IBooksApp booksApp { set; get; }

        [Inject]
        IUsersApp usersApp { get; set; }

        [Inject]
        IBorrowBooksApp borrowBooksApp { get; set; }

        [Inject]
        IMailApp mailApp { get; set; }

        public MenagerController(IBooksApp _booksApp,
            IUsersApp _usersApp,
            IBorrowBooksApp _borrowBooksApp,
            IMailApp _mailApp)
        {
            booksApp = _booksApp;
            usersApp = _usersApp;
            borrowBooksApp = _borrowBooksApp;
            mailApp = _mailApp;
        }

        public ActionResult Index()
        {
            
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                //Ön yüz bilgilerini getirir.
                MenagerIndexModel model = new MenagerIndexModel();
                model.TotalUsers = usersApp.GetAllUsers().Count;
                model.UserRoles = usersApp.GetAllRoles().Count;
                model.TotalBooks = booksApp.GetAllBooks().Count;
                model.LibraryBooks = booksApp.GetAllLibraryBooks().Count;
                model.BorrowBooks = booksApp.GetAllNotLibraryBooks().Count;

                ViewBag.Information = model;
                return View();
            }
        }

        public ActionResult Information()
        {

            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.User = usersApp.GetUser(int.Parse(Session["UserID"].ToString()));
                return View();
            }
        }

        public ActionResult Password()
        {

            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.User = usersApp.GetUser(int.Parse(Session["UserID"].ToString()));
                return View();
            }
        }

       
        [HttpPost]
        public JsonResult MailPasswordSender(int Id)
        {
            if (Session["UserID"] == null)
            {
                return Json(new { result = "danger", message = "Mail gönderilemedi. Oturumunuz sonlanmış olabilir !" });
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return Json(new { result = "danger", message = "Mail sistemde kayıtlı değil !" });
            }
            else
            {
                var user = usersApp.GetUser(int.Parse(Session["UserID"].ToString()));
                string mesaj = "<h4>Kütüphane Yönetim Sistemi</h4> <br/><br/>" +
                        "Kullanıcı Adı : " + user.UserName + " | Şifre : " + user.Password + "<br/><br/>" +
                        "Kullanıcı bilgileri ile giriş yapabilirsiniz.";
                mailApp.MailGonder("Gazi KYS Kullanıcı Bilgileri", mesaj, user.Email);
                //Mailleri gönderdikten sonra mesaj dönüyor.
                return Json(new { result = "success", message = "Kullanıcı bilgileriniz mail olarak gönderildi." });
            }
        }

        [HttpPost]
        public JsonResult UpdateUser(Users user)
        {
            if (user != null)
            {

                if (usersApp.UpdateUser(user))
                {
                    return Json(new { result = "success", message = "Güncelleme İşlemi başarılı." });

                }
                else
                {
                    return Json(new { result = "danger", message = "Güncelleme işleminde hata oluştu." });
                }
            }
            else
            {
                return Json(new { result = "danger", message = "Gönderilen veri boş" });
            }
        }

        #region Kitap İşlemleri

        public ActionResult BookList()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.Authors = booksApp.GetAllAuthors();
                ViewBag.Publishers = booksApp.GetAllPublishers();
                ViewBag.Types = booksApp.GetAllTypes();
                ViewBag.Books = booksApp.GetAllViewBooks();
                return View();
            }
        }

        [HttpPost]
        public JsonResult CreateOrUpdateBook(Books book)
        {
            if (book != null)
            {
                if (booksApp.CreateOrUpdateBook(book))
                {
                    return Json(new { result = "success", message = "İşlem başarılı." });

                }
                else
                {
                    return Json(new { result = "danger", message = "Kitap ekleme işleminde hata oluştu." });
                }
            }
            else
            {
                return Json(new { result = "danger", message = "Gönderilen veri boş" });
            }
        }

        [HttpPost]
        public JsonResult DeleteBook(int Id)
        {
            if (Id != default(int))
            {
                if (booksApp.DeleteBook(Id))
                {
                    return Json(new { result = "success", message = "İşlem başarılı." });

                }
                else
                {
                    return Json(new { result = "danger", message = "Kitap silme işleminde hata oluştu." });
                }
            }
            else
            {
                return Json(new { result = "danger", message = "Gönderilen veri boş" });
            }
        }

        #endregion

        #region Yazar İşlemleri

        public ActionResult AuthorList()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                ViewBag.Authors = booksApp.GetAllAuthors();
                return View();
            }
        }

        [HttpPost]
        public JsonResult CreateOrUpdateAuthor(Authors author)
        {
            if (author != null)
            {
                if (booksApp.CreateOrUpdateAuthor(author))
                {
                    return Json(new { result = "success", message = "İşlem başarılı." });

                }
                else
                {
                    return Json(new { result = "danger", message = "Yazar ekleme işleminde hata oluştu." });
                }
            }
            else
            {
                return Json(new { result = "danger", message = "Gönderilen veri boş" });
            }
        }

        [HttpPost]
        public JsonResult DeleteAuthor(int Id)
        {
            if (Id != default(int))
            {
                if (booksApp.DeleteAuthor(Id))
                {
                    return Json(new { result = "success", message = "İşlem başarılı." });

                }
                else
                {
                    return Json(new { result = "danger", message = "Yazar silme işleminde hata oluştu." });
                }
            }
            else
            {
                return Json(new { result = "danger", message = "Gönderilen veri boş" });
            }
        }

        #endregion

        #region Yayınevi İşlemleri

        public ActionResult PublisherList()
        {
            
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else if (usersApp.GetUser(int.Parse(Session["UserID"].ToString())) == null || usersApp.GetRole(usersApp.GetUser(int.Parse(Session["UserID"].ToString())).RoleID).Name != "Yönetici")
            {
                return RedirectToAction("Index", "Login");

GAZI.LibraryApp.UI/Views/Menager/AuthorList.cshtml
@{
    ViewBag.Title = "AuthorList";
    Layout = "~/Views/Shared/_MenagerLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Tüm Yazar Listesi </font></font></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li style="float:right;">
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div id="datatable_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-xs-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="button" class="btn-sm btn-success" id="btnsifirla" data-toggle="modal" data-target=".bs-example-modal-sm" style="width:175px; margin-bottom:10px;"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Ekle</font></font></button>
                                </div>
                            </div>
                            <table id="datatable" class="table table-striped table-bordered dataTable no-footer" role="grid" aria-describedby="datatable_info">
                                <thead>
                                    <tr role="row">
                                        <th class="sorting_asc" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-sort="ascending" aria-label="">
                                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">ID</font></font>
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="">
                                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Adı</font></font>
                                        </th>
                                        <th class="sorting" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="">
                                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">İşlem Tarihi</font></font>
                                        </th>
                                        <th class="sorting col-md-2" tabindex="0" aria-controls="datatable" rowspan="1" colspan="1" aria-label="">
                                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">İşlemler</font></font>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        foreach (var item in ViewBag.Authors)
                                        {
                                            <tr role="row" class="odd">
                                                <td class="sorting_1"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.ID</font></font></td>
                                                <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.Name</font></font></td>
                                                <td><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">@item.CreateOrModifyDate.ToString("dd.MM.yyyy")</font></font></td>
                                                <td style="padding-left:2.5%;">
                                                    <button type="button" data-toggle="modal" data-target=".bs-example-modal-lg-delete" data-id="@item.ID" class="btn-xs btn-danger frm-delete-yazar col-md-5 col-xs-12"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Sil</font></font></button>
                                                    <button type="button" data-toggle="modal" data-target=".bs-example-modal-sm" data-id="@item.ID" data-name="@item.Name" class="btn-xs btn-info btn-update-yazar col-md-5 col-xs-12"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Güncelle</font></font></button>
                                                </td>
                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>


<div class="modal fade bs-example-modal-sm in" tabindex="-1" role="dialog" aria-hidden="true" style="padding-right: 17px;">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">x</font></font></span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Kayıt Formu</font></font></h4>
            </div>
            <div class="modal-body">
                <form data-parsley-validate="" class="form-horizontal form-label-left" novalidate="">

                    <div class="col-md-10 col-sm-10 col-xs-12">

                        <div class="form-group row">
                            <label class="col-form-label col-md-12 col-sm-12 col-xs-12 label-align" for="first-name">
                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Ad Soyad </font></font>
                            </label>
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <input type="text" id="author_name" placeholder="Yazar Ad Soyad" required="required" class="form-control" value="">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-form-label col-md-12 col-sm-12 col-xs-12 label-align" for="first-name">
                                <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kayıt Tarihi </font></font>
                            </label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <input type="text" placeholder="Kayıt Tarihi" disabled required="required" class="form-control" value="@DateTime.Now.ToString("dd.MM.yyyy")">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-2 col-sm-2 col-xs-0">

                        <div class="form-group row">
                            <br />
                            <div class="col-md-12 col-sm-12 col-xs-12">
                                <div class="profile_img">
                                    <div id="crop-avatar">
                                        <!-- Current avatar -->
                                        <img class="img-responsive avatar-view" src="~/Content/Gentelella/production/images/author.png" alt="Avatar" title="">
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                        
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn-sm btn-danger" data-dismiss="modal"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kapat</font></font></button>
                <button type="button" class="btn-sm btn-success" id="frmaddauthor"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Kaydet</font></font></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-example-modal-lg-delete in" tabindex="-1" role="dialog" aria-hidden="true" style="padding-right: 17px;">
    <div class="modal-dialog modal-lg modal-danger">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">x</font></font></span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Silme Formu</font></font></h4>
            </div>
            <div class="modal-body">
                <h4>Yazarı gerçekten silmek istiyor musunuz?</h4>
                <p>Yazarı sildiğiniz taktirde yazarın bağlı olduğu kitaplar ve kitap kullanıcıya verildiyse bu bilgiler silinecektir!</p>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn-sm btn-info" data-dismiss="modal"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kapat</font></font></button>
                <button type="button" class="btn-sm btn-danger" id="btn-delete-yazar"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Yazar Sil</font></font></button>
            </div>
        </div>
    </div>
</div>

<script src="~/Content/PageScripts/AddAuthor.js"></script>
<script type="text/javascript">
    var submitUrl = "@Url.Action("CreateOrUpdateAuthor", "Menager")";
    var deleteUrl = "@Url.Action("DeleteAuthor", "Menager")";
</script>

GAZI.LibraryApp.UI/Views/Menager/Information.cshtml
@{
    ViewBag.Title = "Kullanıcı Bilgilerim";
    Layout = "~/Views/Shared/_MenagerLayout.cshtml";
    var user = ViewBag.User;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kullanıcı Bilgilerim </font></font></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li style="float:right;">
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-10 col-sm-10 col-xs-12">

                    <div class="form-group row">
                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kullanıcı Adı</font></font>
                        </label>

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Güncellenecek Kayıt Tarihi</font></font>
                        </label>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="1" disabled id="username" data-id="@user.ID" data-roleid="@user.RoleID" placeholder="Kullanıcı Adı" required="required" class="form-control" value="@user.UserName">
                        </div>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" disabled placeholder="Kayıt Tarihi" required="required" class="form-control" value="@DateTime.Now.ToString("dd.MM.yyyy")">
                        </div>
                    </div>

                    <div class="form-group row">

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ad</font></font>
                        </label>

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Soyad</font></font>
                        </label>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="2" id="name" placeholder="Ad" required="required" class="form-control" value="@user.Name">
                        </div>


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="3" id="surname" placeholder="Soyad" required="required" class="form-control" value="@user.SurName">
                        </div>
                    </div>

                    <div class="form-group row">

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">E-Mail</font></font>
                        </label>

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Telefon</font></font>
                        </label>

                        <div class="col-md-5 col-sm-6 col-xs-12">
                            <input type="text" tabindex="4" id="email" placeholder="E-Mail" required="required" class="form-control" value="@user.Email">
                        </div>


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="5" id="telephone" placeholder="Telefon" required="required" class="form-control" value="@user.Telephone">
                        </div>
                    </div>

                    <div class="form-group row">

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Şifre</font></font>
                        </label>

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Şifre Onay</font></font>
                        </label>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="password" tabindex="6" id="password" placeholder="Şifre" required="required" class="form-control" value="@user.Password">
                        </div>


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="password" tabindex="7" id="password_2" placeholder="Şifre Onay" required="required" class="form-control" value="@user.Password">
                        </div>
                    </div>

                </div>

                <div class="col-md-2 col-sm-2 col-xs-0">

                    <div class="form-group row">
                        <br />
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="profile_img">
                                <div id="crop-avatar">
                                    <!-- Current avatar -->
                                    <img class="img-responsive avatar-view" src="~/Content/Gentelella/production/images/user.png" alt="Avatar" title="">
                                </div>
                            </div>
                        </div>

                    </div>

                </div>


                <div class="col-md-12 col-sm-12 col-xs-12">
                    <button type="button" class="btn-sm btn-info col-md-3" style="float:right;" id="btn-update-user"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><i class="fa fa-edit m-right-xs"></i> Bilgilerimi Kaydet</font></font></button>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="~/Content/PageScripts/UpdateUser.js"></script>
<script type="text/javascript">
    var submitUrl = "@Url.Action("UpdateUser", "Menager")";
</script>

GAZI.LibraryApp.UI/Views/Menager/Password.cshtml
@{
    ViewBag.Title = "Şifre Öğrenme Ekranı";
    Layout = "~/Views/Shared/_MenagerLayout.cshtml";
    var user = ViewBag.User;
}

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Şifre Öğrenme Ekranı </font></font></h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li style="float:right;">
                        <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="col-md-10 col-sm-10 col-xs-12">

                    <div class="form-group row">
                        <label class="col-form-label col-md-12 col-sm-12 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Kullanıcı Adı</font></font>
                        </label>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="1" disabled id="username" data-id="@user.ID" placeholder="Kullanıcı Adı" required="required" class="form-control" value="@user.UserName">
                        </div>

                    </div>

                    <div class="form-group row">

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Ad</font></font>
                        </label>

                        <label class="col-form-label col-md-5 col-sm-5 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Soyad</font></font>
                        </label>

                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="2" disabled id="name" placeholder="Ad" required="required" class="form-control" value="@user.Name">
                        </div>


                        <div class="col-md-5 col-sm-5 col-xs-12">
                            <input type="text" tabindex="3" disabled id="surname" placeholder="Soyad" required="required" class="form-control" value="@user.SurName">
                        </div>
                    </div>

                    <div class="form-group row">

                        <label class="col-form-label col-md-12 col-sm-12 col-xs-12 label-align" for="first-name">
                            <font style="vertical-align: inherit;"><font style="vertical-align: inherit;">E-Mail</font></font>
                        </label>

                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <input type="text" tabindex="4" disabled id="email" placeholder="E-Mail" required="required" class="form-control" value="@user.Email">
                        </div>

                    </div>



                </div>

                <div class="col-md-2 col-sm-2 col-xs-0">

                    <div class="form-group row">
                        <br />
                        <div class="col-md-10 col-sm-10 col-xs-12">
                            <div class="profile_img">
                                <div id="crop-avatar">
                                    <!-- Current avatar -->
                                    <img class="img-responsive avatar-view" src="~/Content/Gentelella/production/images/e-mail.png" alt="Avatar" title="">
                                </div>
                            </div>
                        </div>

                    </div>

                </div>


                <div class="col-md-12 col-sm-12 col-xs-12">
                    <button type="button" class="btn-sm btn-info col-md-3" style="float:right;" id="frmmailsender"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;"><i class="fa fa-edit m-right-xs"></i> Şifre Bilgilerimi Gönder</font></font></button>
                </div>
            </div>
        </div>
    </div>

</div>

<script src="~/Content/PageScripts/mailSender.js"></script>
<script type="text/javascript">
    var mailSenderUrl = "@Url.Action("MailPasswordSender", "Menager")";
</script>